### ISSUE TITLE
Drawing board gets cleared when browser window has been resized

### ISSUE THREAD

**Issue by BigETI** [scribble-rs/scribble.rs#106]
Drawing board gets cleared when the parent browser window has been resized.

**Comment by Bios-Marcel** [comment]
This is a known issue and I couldn't think of a solution that I really like. Caching the drawing is very memory-intensive, especially since we don't know the amount of drawing instructions beforehand. Meaning we have to gradually allocate more and more memory. Maybe we could at a fixed interval check for resizes and ask the server to re-send us the image? I am not sure. If you have a better idea, I am open to it. Maybe micro-optimizing some stuff could already help. For example I am unsure whether having many objects with long variable names will take more memory than having objects where each field is a single letter. I simply have no fucking clue how JS is implemented :D

Maybe I should get to know the details a bit better, since this a very different environment from what I am used to.

**Comment by SZenglein** [comment]
It might be worth completely redesigning the drawing with scaling, different screen sizes and multiple platforms in mind.

There was the idea of defining a minimum canvas size, e.g. 800x600 which clients should only scale in integer steps (1600x1200, 2400x1800). 

Drawing instructions would only be applied to the minimum canvas size so that all clients can draw it.

Pros:
- the canvas does not need to be resized as often
- easier to test, as there are not as many canvas sizes
- does never lead to blurry half-pixels
- high-dpi clients can still draw at a higher resolution
- drawing looks very similar on every screen
Cons:
- minimum drawing resolution should be fairly low
- high DPI clients are limited in their drawing resolution
- Drawing could still look slightly different with different scaling

Because resizing the canvas would occur less often and would be more predictable, it would be easier to implement properly.

I think for this drawing game it is important that everyone sees the same image. So the highest priority should be that the drawing is consistent. If that means the canvas needs a fixed size, so be it.

**Comment by BigETI** [comment]
Best solution would be to have a fixed size image buffer just for drawing operations, and such buffer can be applied as a texture for any kind of surface, like a scalable canvas. In this case every client must have an internal buffer and render it on a scalable surface with fixed aspect ratio to keep draw contents visually consistent. Rasterized drawing operations can be designed to be highly parallel. Either by using multiple CPU cores or just compute each pixel with a compute shader, which then would run on GPU.

**Comment by SZenglein** [comment]
That was my initial idea. It should be kept in mind that freely scaling as desired might lead to scaling issues, but those are probably negligible (and clients can still decide to only scale in integer steps). 

Nevertheless, I would support this solution for its simplicity and consistency of drawing.


For simple drawing and filling, IMO using compute shaders and such would be overkill.

**Comment by SZenglein** [comment]
That was my initial idea. It should be kept in mind that freely scaling as desired might lead to scaling issues, but those are probably negligible (and clients can still decide to only scale in integer steps). 

Nevertheless, I would support this solution for its simplicity and consistency of drawing.


For simple drawing and filling, IMO using compute shaders and such would be overkill.

**Comment by Bios-Marcel** [comment]
Fixed with 3072daa
