### ISSUE TITLE
Zoom and zoom out page will clear board.

### ISSUE THREAD

**Issue by Ahmadrezadl** [scribble-rs/scribble.rs#142]
Also changing window size.

**Comment by Bios-Marcel** [comment]
Thanks, this bug is known and is an issue with the canvas API. Sorry for the late reply. Either way, the workaround here is probably requesting the data from the backend again. However, this might not be super easy, as pieces of information could be incorrectly applied. A different solution might be to fix the canvas in size, however, that might be hacky.

**Comment by Bios-Marcel** [comment]
Also possible to happen when switching browser tabs. Even more of a reason to fix it timely.
