### ISSUE TITLE
Popup Window with Highscore table, new game and exit button at the end of the game

### ISSUE THREAD

**Issue by kosta-pag** [scribble-rs/scribble.rs#154]
It would be handy if there was a popup window with a highscore table, restart and exit button at the end of the game

**Comment by Bios-Marcel** [comment]
When you say highscore, do you mean highscores across rounds? Because this would require some kind of data store. Currently scribble.rs is fully ephemeral, no data is stored.

**Comment by kosta-pag** [comment]
Yes I mean highscores across rounds. Only for the player in the lobby.

**Comment by Bios-Marcel** [comment]
A round refers to every player drawing once from top to bottom of the player list. A game consists of all rounds being played played out.

So, when you say across rounds, you mean in the context of a single game, not multiple games or even multiple games in multiple different lobbies? So, do you mean a prominent display of the highest scores of all players in the lobby after having played out all rounds, e.g. having finished the game? E.g. a winners podium? Because if you mean personal highscores accross rounds or even games, I don't see much of a point in that, as drawings, time limits and so on and so forth usually differ between rounds.

Just making sure I understand right, otherwise I can't properly implement anything ;)
It usually helps if I get a little mockup, drawn with paint or whatever you prefer.

**Comment by kosta-pag** [comment]
Hello 
I draw an example. This showsa winners podium at the end of the match. Like this 
![Score](https://user-images.githubusercontent.com/55231330/104093820-4d8ec280-528d-11eb-8ecf-d9b9fffd9daf.png)

sorry for my bad sketch

**Comment by Bios-Marcel** [comment]
It's fine, now I know exactly that you mean what I thought ^^
