### ISSUE TITLE
Transfer Host Role

### ISSUE THREAD

**Issue by glauni** [scribble-rs/scribble.rs#192]
What is the current behavior when a host leaves the room? Is the host role transferred to another player? Might be a good idea to have an option for that.

This should happen in case of internet loss or something like that.

**Comment by Bios-Marcel** [comment]
There is no host, but just an owner / creator. Meaning you won't run into the case where the "host" leaves the lobby and the lobby has to do a host migration and pause the game or something like that. Just making sure the difference is clear :)

A disconnect will retain the owners player entry, therefore the owner can reconnect. Either way, I dislike the current "owner" concept, which is why I made #187 

The owner can currently do two things, restarting and changing the max player count. I'll probably just drop the max player count changing feature, cause it's rarely useful I think.

**Comment by Bios-Marcel** [comment]
Closing this, as #187 has been resolved.
