### ISSUE TITLE
Spectator Mode

### ISSUE THREAD

**Issue by glauni** [scribble-rs/scribble.rs#201]
It would be very cool if you had the possibility to invite spectators into your room - so they don't have to paint but can follow the game.

**Comment by Bios-Marcel** [comment]
Should they be visible somewhere, maybe just as a count, for example: `Spectators: 6`.
I assume they shouldn't waste space in the scoreboard.

Also, how'd a spectator join? Currently a spectator wouldn't be able to join an already full lobby.
So, we'd need like a pre-screen where you it says `The lobby is full, but CLICK HERE to spectate instead`.
On top of that we'd need a dialog that asks you whether you want to spectate or not and a spectator also needs a button to jump into the game.

Sounds like quite the big feature ^^

Any specific feedback or ideas regarding that?

**Comment by benl96** [comment]
I think that a small text indicating how many viewers are present can not hurt. But it should not waste space in the scoreboard.

I guess that would be the ideal case, to be able to say during the lobby that you are a spectator or not. You would then invite a player to the lobby and he would have the option to decide if he is a spectator or a player. (Of course, only after a completed round there is the possibility to change this decision).
If a game is already in progress and someone enters the link, you could automatically make him a spectator - he would then have the opportunity to join the game after the end of the round.

Would be a bigger feature, that's true.

**Comment by Bios-Marcel** [comment]
So, I was thinking maybe not make players spectators initially as that could be somewhat annoying.
Instead allow to switch into spectators at any time, but only switch back as soon as the next turn starts.
If a lobby is already full, you'll get an error and be offered to join as a spectator instead, since not everyone might want to spectate.
On top of that, even if the lobby was full when you joined as a spectator, you need should be able to take over a vacant spot while obeying the rules that players, which attempt to join, have to obey.

On top of that, this has to be available to third party clients, since we are working on an official mobile client.
Also not sure where the spectator info label should go. Maybe above the scoreboard or the chat?

**Comment by benl96** [comment]
Sounds good to me. 
The point with taking over a spot even if the lobby was full would make gathered points kind of useless if u missed some rounds before, so a spectator that enters a game later on will always have trouble to win a game, right?

I'd indicate a spectator label/icon in the players name box in the scoreboard
Depends on the name length but usually we have some free space in the name box below the scoreboard, might be an option to do it there. Otherwhise i'd probably look at a rather large label below the whole color selection / erase thingy toolbar that says something like Youre spectating.

**Comment by Bios-Marcel** [comment]
Better late than never :D

**Comment by Bios-Marcel** [comment]
Follow-up improvement issue: #334
