### ISSUE TITLE
Spam filter.

### ISSUE THREAD

**Issue by fuwn** [scribble-rs/scribble.rs#246]
An option within the lobby preferences to filter spam plus possible "inappropriate" names.

**Comment by Bios-Marcel** [comment]
Partial dupe of #15 

The inappropriate name thing is kinda difficult to implement I think. Do you have any ideas for that? Because I see potential problems with intentional typos and the fact that you can use whatever language or even numbers and lookalike characters.
I don't feel like this is a problem worth solving in that regard.

**Comment by Bios-Marcel** [comment]
#15 is being left open
