### ISSUE TITLE
Grid design and UI elements are broken in IE on Win 8

### ISSUE THREAD

**Issue by MarvinKlar** [scribble-rs/scribble.rs#29]
All the elements (Round, time left, player names & scores, draw canvas, color palette, chat box) are alligned from top to bottom (in this order). This causes to make the game unplayable on this setup.

Also, some ui elements seem to not be displayed correctly.
![2019-07-10 08_44_41-Scribble rs - Game - Internet Explorer](https://user-images.githubusercontent.com/34421947/60946947-c0f9f180-a2ef-11e9-9beb-fe5743b2e9e7.png)

Javascript errors:
SCRIPT1002: Syntaxfehler
Datei: lobby, Zeile: 260, Spalte: 32

**Comment by Bios-Marcel** [comment]
Dont care. If someone uses IE, he can rot for all I care :)

**Comment by MarvinKlar** [comment]
I'll try to fix that anyway, since I'm not a (that) discriminating person like u ;P I know that a lot of companies which have the IE as default (or only) browser and I don't want to exclude that poor souls working there.

**Comment by Bios-Marcel** [comment]
It has nothing to do with discrimination. I simply don't want to support an unsupported browser. You can't fix it unless you redo the whole layout.Internet Explorer simply doesn't support css grid, which is what I used for the layout.

If you wanna do that and you wanna do it responsively, try using flexbox and make it responsive enough to fit multiple browser sizes as well. The problem here is having to resize the canvas and keeping everything left and top of the canvas constant during the game, since otherwise the canvas will jump, basically making it super annoying to draw.
