### ISSUE TITLE
Two player points are broken

### ISSUE THREAD

**Issue by ABirdCoder** [scribble-rs/scribble.rs#306]
# Points = Broken
I'm just playing with my friend and I notice points are broken in the game....

[insert image here]

Basically, our points **ALWAYS** stay the same, meaning nobody wins.

I'm assuming this happens because it awards the same amount of points to those who guessed the drawing, and those that drew the drawing.

If you can't fix this, I can always take a shot!

**Comment by Bios-Marcel** [comment]
What's your suggestion for a fair scoring system then?

**Comment by Bios-Marcel** [comment]
I really think that 1v1 is quite the edge case. I don't see a point in drawer and guesser not getting the same points. This game is best played at 4+ people I think and it doesn't make sense optimising it for 1v1. And I also don't see the point in giving the drawer N points for every person that guessed it, if everyone took 95% of the time guessing it right, because that means the drawing probably sucked. I think it's not really possibly to have an algorithm that suites all scenarios, unless you have super cool machine learning algorithm maybe :D
