### ISSUE TITLE
Release binaries are not static

### ISSUE THREAD

**Issue by kovmir** [scribble-rs/scribble.rs#335]
```
$ ldd scribblers-linux-x64
        /lib64/ld-linux-x86-64.so.2 (0x7f37a864c000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f37a864c000)
Error relocating scribblers-linux-x64: __vfprintf_chk: symbol not found
Error relocating scribblers-linux-x64: __fprintf_chk: symbol not found
```

**Comment by Bios-Marcel** [comment]
Hm, interesting.

I might need some more information about your system. What version of libc and such? Are you using musl?

Anything else relevant maybe?

**Comment by kovmir** [comment]
I am on [alpine](https://alpinelinux.org/), it does use `musl`, but it does not matter. [Here](https://www.arp242.net/static-go.html) is a good manual describing how to build static Go binaries, either disable `CGO`, or link statically against `musl`.

**Comment by Bios-Marcel** [comment]
To be honest, this is kind of why I supply the docker container. I specifically didn't want to care about the binaries. I might adjust the readme a bit regarding this.

If they don't work for you, they are super easy to compile yourself. IF the docker image doesn't work for you however, I am willing to fix that right away.

I don't want to use `netgo` and `osgo` either, since i don't know whether this could have any downsides or changes in behaviour in any way. I can't really be bothered testing everything in multiple setups either. Hope you understand :)

**Comment by Bios-Marcel** [comment]
A clarification has been added with this commit: bf7291b19545597d9603d564e362a08cbd512849

**Comment by kovmir** [comment]
Dude, it is just `CGO_ENABLED=0 go build ./cmd/scribblers`, and you are done:

```
$ CGO_ENABLED=0 go build ./cmd/scribblers
$ ldd ./scribblers
        not a dynamic executable
```

To automate it, push such a `Makefile`:

```makefile
build:
	CGO_ENABLED='0' go build ./cmd/scribblers

clean:
	rm -f ./scribblers
```
Now simply invoke `make` to compile a static binary.

**Comment by kovmir** [comment]
Moreover, you can make GitHub Actions automatically compile the static binary and attach the artifacts to each release.
