### ISSUE TITLE
Votekicking the creator of the lobby crashes the server

### ISSUE THREAD

**Issue by L-as** [scribble-rs/scribble.rs#60]
I get this error:
```
(the below line thousands of times)
2020/03/23 20:17:12 Error reading from socket: read tcp 192.168.1.3:8008->80.196.9.102:57534: use of closed network connection
2020/03/23 20:17:12 Error reading from socket: read tcp 192.168.1.3:8008->80.196.9.102:57534: use of closed network connection
2020/03/23 20:17:12 Error reading from socket: read tcp 192.168.1.3:8008->80.196.9.102:57534: use of closed network connection
panic: repeated read on failed websocket connection

goroutine 142 [running]:
github.com/gorilla/websocket.(*Conn).NextReader(0xc000378580, 0x54f280, 0xc0000e0000, 0x2, 0xc0005a59d0, 0x6b)
	/build/go/pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:967 +0x353
github.com/gorilla/websocket.(*Conn).ReadMessage(0xc000378580, 0x1e, 0xc000473f68, 0x1, 0x1, 0x906a00, 0xc0000e0e60)
	/build/go/pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:1028 +0x2f
main.wsListen(0xc0000f2000, 0xc000148080, 0xc000378580)
	/build/scribble.rs/lobby.go:190 +0x43
created by main.wsEndpoint
	/build/scribble.rs/lobby.go:177 +0x2cf
```

**Comment by hija** [comment]
I can confirm this, but I think it the bug description is a bit misleading. In my test case (2 clients; each with the same ip address) the server crashed whenever a user was kicked. It was not a requirement that the kicked user is the host. I will have a look...

**Comment by hija** [comment]
Okay, I think I found the mistake.

https://github.com/scribble-rs/scribble.rs/blob/6787e2c09da295c2e3d0f117a4bd01c2a336ec34/lobby.go#L199

I think we are missing a return here: If the connection is closed and the reason is not IsCloseError or IsUnexpectedCloseError, we print out the "Error reading from socket" information. But we stay in the while ("for") loop. I think we should move the return statement out of the if block, so that we return as soon as an error occured. @Bios-Marcel, your opinion on this one?

**Comment by Bios-Marcel** [comment]
I just added a workaround for this. In my opinion gorilla/websocket is to blame for this one, since calling `Close()` on the socket won't result in a `CloseError` when calling `ReadMessage()`. The workaround for now is catching the panning and either returning or rethrowing it depending on which error it was.

I am gonna try updating gorilla, seeing whether that changes anything, but I doubt.

**Comment by Bios-Marcel** [comment]
Nope, updating it doesn't seem to help.

**Comment by hija** [comment]
I still think we should move the return statement into the upper code bracket. If an unexpected error occurs, I do not see any reason why we should still try to read from that websocket.

**Comment by Bios-Marcel** [comment]
Well, I thought that an error might not necessarily mean that the connection is broken or anything. So I wanted to avoid breaking the game in such a case.

**Comment by hija** [comment]
What error would you expect which is not related to a broken connection? I just looked up the documentation and did not find such a case. But maybe I was just looking wrong :)

**Comment by Bios-Marcel** [comment]
I'd actually like to get a panic in unexpected cases, that's all I itended. I don't want there to be any chance that a bug goes unnoticed, even if it the world crashes :D 

And I assume that there could always be weird bugs on underlying layers or something like that, no matter whether it is likely or not. But yeah ... maybe you are right and we should just return. It'd be cool if I had some way of getting notified if it is not just "connection already closed ....".

**Comment by Bios-Marcel** [comment]
I'll just solve it by hardcoding this error as an accepted problem. This way I'll deffo not obfuscate other bugs.
